###### To solve a puzzle, you are given an initial state and a goal state.
###### Target is to reach goal state from initial state using puzzle rules.
######  We can move blank tile only on left, right, up, and down
![Capture.JPG](attachment:Capture.JPG)

# Generate an intial state of NPuzzle

In [1]:
import numpy as np
import random
def get_state(N):    
    state = [item for item in range(N*N)]# [0,1,2,...,15]
    #print(state)
    random.shuffle(state)
    #print(state)
    tmp = np.array(state)
    print(tmp.reshape(N,N))
    return state

In [2]:
get_state(4)

[[10 11  6  2]
 [ 1  4 15  5]
 [13  8  3  0]
 [ 9  7 12 14]]


[10, 11, 6, 2, 1, 4, 15, 5, 13, 8, 3, 0, 9, 7, 12, 14]

# Calculate inversion

Inversion is a pair of tiles that are in the reverse order from where they ought to be. In our case, the bigger number is in front of the smaller one.



![Capture.JPG](attachment:Capture.JPG)

In [3]:
def count_inversion(state):
    #arr = [i for i in arr if i !=0]
    print(state)
    inversion = []
    for i in range(len(state)):    
        count = 0
        for j in range(i+1,len(state)):        
            if state[i] > state[j]: 
                count = count + 1
        inversion.append(count)
    #print(inversion)
    return sum(inversion)

In [4]:
s = get_state(4)
count_inversion(s)

[[ 0  3  7 15]
 [ 8 12  6  1]
 [11 14  5  9]
 [ 4 10  2 13]]
[0, 3, 7, 15, 8, 12, 6, 1, 11, 14, 5, 9, 4, 10, 2, 13]


53

# **Find blank row**

In [9]:
N=5


In [10]:
S=get_state(N)

[[18 13  9 11  0]
 [ 6 16  8 21  2]
 [ 4 17  1  5 12]
 [22  3 14 19 10]
 [ 7 20 15 23 24]]


In [11]:
def get_blank_row(state):
    a = N - int(state.index(0) / N)
    return a

In [12]:
get_blank_row(S)

5

# Solvability Rules

In [13]:
# apply the rules to decide solvability
#  N, I, R
# define a method to return solvability (input S)
# return True if solvable or False if not

def isSolvable(initialState):
    I=count_inversion(initialState)
    N=5
    R = get_blank_row(initialState)
    
    if(N%2!=0): 
        if(I%2==0): return True
        else: return False
        
    else:
        if(I%2==0 and R%2!=0): return True
        elif(I%2!=0 and R%2==0): return True
        else: return False
  



In [14]:
S = get_state(N)
isSolvable(S)


[[23 15  2 10  7]
 [11 12 14  9 24]
 [20 16 17  5  6]
 [21  1 19 13  4]
 [ 0  8 22  3 18]]
[23, 15, 2, 10, 7, 11, 12, 14, 9, 24, 20, 16, 17, 5, 6, 21, 1, 19, 13, 4, 0, 8, 22, 3, 18]


True